In [1]:
import numpy as np

In [4]:
def add_vectors(u,v):
    """>>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
      """
    print(add_vectors)

In [40]:
#load library
import numpy as np

u=np.array([1, 0])
v=np.array([1,1])
x=np.add(u,v)

print(x)

[2 1]


In [41]:
#load library
u=np.array([1, 2, 1])
v=np.array([1, 4, 3])
y=np.add(u,v)

print(y)

[2 6 4]


In [42]:
#load library
u=np.array([11, 0, -4, 5])
v=np.array([2, -4, 17, 0])
z=np.add(u,v)

print(z)

[13 -4 13  5]


In [43]:
np.array([1,2])*5


array([ 5, 10])

In [44]:
np.array([1,0,-1])*3


array([ 3,  0, -3])

In [45]:
np.array([3,0,5,11,2])*7


array([21,  0, 35, 77, 14])

In [46]:
np.array([1,2,3])*(4,a)


NameError: name 'a' is not defined

In [49]:

x=np.array([1,1])
y=np.array([1,1])
z=np.dot(x,y)

print(z)

2


In [50]:
x=np.array([1,2,1])
y=np.array([1,4,3])
z=np.dot(x,y)

print(z)

12


In [51]:
x=np.array([2,0,-1,1])
y=np.array([1,5,2,0])
z=np.dot(x,y)

print(z)

0


In [54]:
x=np.array([[1,2],[3,4]])
np.copy(x)


array([[1, 2],
       [3, 4]])

In [56]:
x=np.array([[1, 2, 3], [4, 5, 6]])
np.copy(x)

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
y=np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
np.copy(y)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [61]:
m=np.array([[0, 0], [0, 0]])

np.addrow(m)

AttributeError: module 'numpy' has no attribute 'addrow'

In [85]:
def add(m1,m2):

 m1=np.matrix(m1)
 m2=np.mat(m2)
 return m1+m2
add([[1,2],[3,4]],[[2,2],[2,2]])

matrix([[3, 4],
        [5, 6]])